services:
  weather-server:
    build:
      context: ./weather-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    ports:
      - "11435:11435"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /usr/share/ollama/.ollama:/usr/share/ollama/.ollama

volumes:
  ollama_data: