services:
  pdb-server:
    build:
      context: ./protein-data-bank
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"

  ollama:
    image: ollama/ollama:latest
    runtime: nvidia
    ports:
      - "11435:11435"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - /usr/share/ollama/.ollama:/usr/share/ollama/.ollama

volumes:
  ollama_data: